<?php

/**
 * @file
 * install functionality
 *
 * Contains all install related functionality
 */


/**
 * Implements hook_uninstall().
 */
function islandora_solr_facet_pages_uninstall() {
  // Remove variables.
  $variables = array(
    'islandora_solr_facet_pages_fields_data',
    'islandora_solr_facet_pages_limit',
    'islandora_solr_facet_pages_facet_limit',
  );
  foreach ($variables as $variable) {
    variable_del($variable);
  }
}
