<?php

/**
 * @file
 * Various hook and function implementations.
 */

/**
 * Implements hook_init().
 */
function islandora_solr_facet_pages_init() {
  // Include islandora_solr common.inc.
  module_load_include('inc', 'islandora_solr', 'includes/utilities');
  // Include islandora solr query_processor.inc
  module_load_include('inc', 'islandora_solr', 'includes/query_processor');
}

/**
 * Implements hook_menu().
 */
function islandora_solr_facet_pages_menu() {
  $items = array();
  $url_alias = '';
  $fields = variable_get('islandora_solr_facet_pages_fields_data', array());
  foreach ($fields as $key => $value) {
    $url_alias = (string)$value['url_alias'];
    if((string)$value['view_mode'] === 'Page'){
      $items["$url_alias"] = array(
        'title' => t($value['label']),
        'description' => 'Facet Item',
        'menu_name' => 'main-menu',
        'page callback' => 'islandora_solr_facet_pages_callback',
        'page arguments' => array(2, 3, 4),
        'access callback' => 'islandora_solr_facet_pages_access_callback',
        'access arguments' => array(2),
        'type' => MENU_CALLBACK,
      );
    }
  }
  /*$items['browse'] = array(
    'page callback' => 'islandora_solr_facet_pages_callback',
    'page arguments' => array(1, 2, 3),
    'access callback' => 'islandora_solr_facet_pages_access_callback',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );*/
  $items['admin/islandora/search/islandora_solr/facet_pages'] = array(
    'title' => 'Facet Pages',
    'description' => 'Islandora Solr facet pages settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_solr_facet_pages_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'islandora_solr_facet_pages.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function islandora_solr_facet_pages_theme() {
  // Set path.
  $base = array(
    'path' => drupal_get_path('module', 'islandora_solr_facet_pages') . '/theme',
    'file' => 'islandora_solr_facet_pages.theme.inc',
  );

  return array(
    'islandora_solr_facet_pages_wrapper' => $base + array(
      'template' => 'islandora-solr-facet-pages-wrapper',
      'variables' => array(
        'letterer' => NULL,
        'results' => NULL,
        'pager' => NULL,
        'path' => NULL,
        'pager_data' => array(),
        'url_alias' => NULL,
        'show_a_z' => NULL,
      ),
    ),
    'islandora_solr_facet_pages_results' => $base + array(
      'template' => 'islandora-solr-facet-pages-results',
      'variables' => array(
        'results' => array(),
        'solr_field' => NULL,
        'path' => NULL,
        'url_alias' => NULL,
      ),
    ),
    'islandora_solr_facet_pages_letterer' => $base + array(
      'variables' => array(
        'facet_queries' => array(),
        'fq_map' => array(),
        'prefix' => NULL,
        'path' => NULL,
        'url_alias' => NULL,
        'view_mode' => NULL,
      ),
    ),
    'islandora_solr_facet_pages_admin_table' => array(
      'file' => 'islandora_solr_facet_pages.admin.inc',
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_solr_facet_pages_block_info() {
  $blocks = array();
  $blocks['islandora-solr-facet-pages'] = array(
    'info' => t('Islandora Solr facet pages'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $fields = variable_get('islandora_solr_facet_pages_fields_data', array());
  foreach ($fields as $key => $value) {
    $path = str_replace('/','-',(string)$value['path']);
    
    if(!empty($path)&&!empty($value['view_mode'])){
      if($value['view_mode'] === 'Block'){
        $block_info_string = "Islandora Solr facet ".$value['label'];
        $block_name = "islandora-solr-facet-$path";
        $blocks["$block_name"] = array(
          'info' => t("$block_info_string"),
          //'cache' => DRUPAL_NO_CACHE,
        );
      }
    }
  }
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function islandora_solr_facet_pages_block_view($delta = '') {
  $block = array();
  $path = '';
  $fields = variable_get('islandora_solr_facet_pages_fields_data', array());
  $current_url = trim(drupal_get_path_alias());
  
  foreach ($fields as $key => $value) {
    $path = (string)$value['path'];
    $url_alias = $value['url_alias'];
    $target_url = trim($url_alias . '/' .$path);
    if(!empty($path)&&!empty($value['view_mode'])){
      if($value['view_mode'] === 'Block'){
        $block_info_string = "Islandora Solr facet ".$value['label'];
        $block_name = "islandora-solr-facet-$path";
        if($delta == $block_name){
          $params = drupal_get_query_parameters();
          
            $prefix = NULL;
            $mode = NULL;
            if (isset($params['mode']) && !empty($params['mode']) && $params['mode'] === $path) {
              $mode = $params['mode'];
            }else{
              $mode = $path;
            }
            if (isset($params['prefix']) && !empty($params['prefix'])) {
              $prefix = $params['prefix'];
            }
            if(islandora_solr_facet_pages_access_callback($mode)){
              $block['subject'] = t('Islandora Solr facet pages');
              $block['content'] = islandora_solr_facet_pages_callback($mode,$prefix);
              break;
            }
        }else if($delta == 'islandora-solr-facet-pages'){
          $block['subject'] = t('Islandora Solr facet pages');
          $block['content'] = islandora_solr_facet_pages_block_callback();
          break;
        }
      }
    }
  }
  return $block;
}

/**
 * Performs a solr query to get facets fields for the alphabetical pager.
 *
 * It makes use of facet queries.
 *
 * @param object $solr
 *   Apache_Solr_Service object to use for the facet query.
 * @param string $solr_field
 *   Solr field to use for the facet query.
 * @param string $search_term
 *   Term to search facets with.
 *
 * @return array
 *   Returns array containing facet_queries and a filter query map. Both arrays
 *   are used to theme the alphabetical pager. The fq_map contains an array
 *   which maps a filter query to a prefix. eg: solr_field:A* => A.
 *   Facet_queries are the solr results wich maps the filter query to the bucket
 *   size, eg: solr_field:A* => 1234
 */
function islandora_solr_facet_pages_build_letterer($solr, $solr_set, $search_term = NULL) {
  $solr_build = new IslandoraSolrQueryProcessor();
  $fq = array();
  $fq_map = array();
  $solr_field = $solr_set['solr_field'];
  $limit_field = $solr_set['limit_field'];
  $limit_value = $solr_set['limit_value'];
  foreach (range('A', 'Z') as $letter) {
    $value = "$solr_field:($letter* OR " . strtolower($letter) . "*)";
    $fq_map[$value] = $letter;
    $fq[] = $value;
  }
  // Set facet parameters.
  $params = array(
    'facet' => 'true',
    'facet.field' => $solr_field,
    'facet.sort' => 'index',
    'facet.mincount' => 1,
    'facet.limit' => 0,
    'facet.query' => $fq,
    'qt' => variable_get('islandora_solr_request_handler', 'standard'),
    'hl' => 'false',
  );

  // Set query.
  $search_term = trim($search_term);
  if ($search_term) {
    $query = "$solr_field:($search_term)";
  }
  else {
    $query = "$solr_field:[* TO *] AND $limit_field:$limit_value";
  }
  $solr_build->buildQuery($query, $params);
  // Because IslandoraSolrQueryProcessor stomps on our facet params.
  $solr_build->solrParams = array_replace_recursive($solr_build->solrParams, $params);
  try {
    $solr_build->executeQuery();
    // Facet queries.
    $facet_queries = $solr_build->islandoraSolrResult['facet_counts']['facet_queries'];
  }
  catch (Exception $e) {
    $facet_queries = new stdClass();
    drupal_set_message(check_plain(t('Error searching Solr index')) . ' ' . $e->getMessage(), 'error', FALSE);
  }

  return array(
    'facet_queries' => $facet_queries,
    'fq_map' => $fq_map,
  );
}

/**
 * Performs a solr query to return facet_fields to populate the results page.
 *
 * @param object $solr
 *   Apache_Solr_Service object to use for the facet fields query.
 * @param string $solr_field
 *   Solr field to use for the facet fields query.
 * @param string $prefix
 *   Prefix from the URL to add to add a prefix to the facet query. This will
 *   limit the returned fields with fields that are prefixed with this value.
 * @param string $search_term
 *   Term to search facets with.
 *
 * @return array
 *   Returns an array of all the facet field values and the bucket size: eg:
 *   solr value => 123
 */
function islandora_solr_facet_pages_build_results($solr, $solr_set, $prefix, $search_term = NULL) {
  $solr_build = new IslandoraSolrQueryProcessor();
  // Get the actual results.
  $search_term = trim($search_term);
  $solr_field = $solr_set['solr_field'];
  $limit_field = $solr_set['limit_field'];
  $limit_value = $solr_set['limit_value'];
  if ($search_term) {
    $query = "$solr_field:($search_term)";
  }
  else {
    $query = "$solr_field:[* TO *] AND $limit_field:$limit_value";
  }

  // Set facet parameters.
  $facet_params = array(
    'facet' => 'true',
    'facet.field' => $solr_field,
    'facet.sort' => 'index',
    'facet.mincount' => 1,
    'facet.limit' => variable_get('islandora_solr_facet_pages_facet_limit', 100000),
    'qt' => variable_get('islandora_solr_request_handler', 'standard'),
    'hl' => 'false',
  );

  // Set the facet prefix.
  if ($prefix != t('ALL') && strtolower($prefix) != 'chinese') {
    $facet_params['facet.prefix'] = $prefix;
  }
  $solr_build->buildQuery($query, $facet_params);
  $solr_query = ($solr_build->internalSolrQuery) ? $solr_build->internalSolrQuery : $solr_build->solrQuery;
  // Because the IslandoraSolrQueryProcessor stomps on our facet information.
  $solr_build->solrParams = array_replace_recursive($solr_build->solrParams, $facet_params);
  try {
    $solr_build->executeQuery();
    $fields = (array) $solr_build->islandoraSolrResult['facet_counts']['facet_fields'][$solr_field];
  }
  catch (Exception $e) {
    $fields = array();
    drupal_set_message(check_plain(t('Error searching Solr index')) . ' ' . $e->getMessage(), 'error', FALSE);
  }

  return $fields;
}

/**
 * Prepares data to render the pager.
 *
 * @param array $result_fields
 *   An array containing all the results.
 *
 * @return array
 *   Returns an array containing values to configure and render the pager.
 *   Limit, offset and total.
 */
function islandora_solr_facet_pages_pager($result_fields = array()) {
  // Set variables.
  $limit = variable_get('islandora_solr_facet_pages_limit', 25);
  $offset = 0;
  $total = NULL;

  // Get URL parameters.
  $params = $_GET;
  unset($params['q']);

  // Get page limit.
  if (!empty($limit)) {
    $total = count($result_fields);
    $offset = isset($params['page']) ? $params['page'] * $limit : 0;
    pager_default_initialize($total, $limit);
  }

  return array(
    'limit' => $limit,
    'offset' => $offset,
    'total' => $total,
  );
}

/**
 * Page callback function.
 *
 * @param string $path
 *   Machine readable name passed in the url to decide what solr field to facet
 *   on.
 * @param string $prefix
 *   Letter of the alphabet to filter on.
 *
 * @return string
 *   Rendered page including letter pager, numerical pager and search results.
 */
function islandora_solr_facet_pages_callback($path = NULL, $prefix = NULL, $search_term = NULL) {
  // Get available fields from variable.
  $current_url = drupal_get_path_alias();
    
  $fields = variable_get('islandora_solr_facet_pages_fields_data', array());
  //print_r($fields);
  // Callback validation.
  $url_alias = "";
  $view_mode = "block";
  $show_a_z = 1;
  foreach ($fields as $key => $value) {
    if ($path == $value['path']) {
      $view_mode = (string)$value['view_mode'];
      $url_alias = (string)$value['url_alias'];
      //print($url_alias.'/'.$value['path']);
      $solr_set['solr_field'] = $value['solr_field'];
      $solr_set['limit_field'] = $value['limit_field'];
      $solr_set['limit_value'] = $value['limit_value'];
      $show_a_z = (int)$value['show_a_z'];
      if($view_mode === "Page"){
        drupal_set_title($value['label']);
      }
    }
  }

  // Set default prefix.
  if ($prefix == NULL) {
    $prefix = t('ALL');
  }

  // Include base CSS file.
  $base_css = drupal_get_path('module', 'islandora_solr_facet_pages') . '/css/islandora_solr_facet_pages.base.css';
  drupal_add_css($base_css);

  // Use Solr faceting to get list of names.
  $parsed_url = parse_url(variable_get('islandora_solr_url', 'http://localhost:8080/solr'));
  $solr = new Apache_Solr_Service($parsed_url['host'], $parsed_url['port'], $parsed_url['path']);

  // Render letters.
  if($show_a_z === 1){
    $letterer_arr = islandora_solr_facet_pages_build_letterer($solr, $solr_set, $search_term);
    //print($letterer_arr['facet_queries'].' '.$letterer_arr['fq_map'].' '.$prefix.' '.$path.' '.$url_alias);
    $letterer = theme('islandora_solr_facet_pages_letterer', array(
      'facet_queries' => $letterer_arr['facet_queries'],
      'fq_map' => $letterer_arr['fq_map'],
      'prefix' => $prefix,
      'path' => $path,
      'url_alias' => $url_alias,
      'view_mode' => $view_mode,
    ));
  }
  // Collect results.
  $result_fields = islandora_solr_facet_pages_build_results($solr, $solr_set, $prefix, $search_term);
  // Collect results with lowercase.
  //print_r($result_fields);
  $prefix_lower = strtolower($prefix);
  $result_fields_lower = islandora_solr_facet_pages_build_results($solr, $solr_set, $prefix_lower, $search_term);
   //print_r($result_fields_lower);
  // Merge uppercase with lowercase.
   if(!empty($result_fields_lower) && isset($result_fields_lower)){
     $result_fields_merge = array_merge($result_fields, $result_fields_lower);
   }else{
     $result_fields_merge = $result_fields;
   }
  
  // Set the facet prefix.
  if (strtolower($prefix) == 'chinese') {
    $replace_string = "/^[^a-zA-Z]/";
    foreach($result_fields_merge as $key => $value){
      //echo $key . ' ';
      $key_string = $key;
      if(preg_match("/^[^a-zA-Z]/",$key) == 0){
        unset($result_fields_merge[$key]);
      }
    }
  }
  
  // Set up pager.
  $pager_data = islandora_solr_facet_pages_pager($result_fields_merge);
  $offset = $pager_data['offset'];
  $limit = $pager_data['limit'];
  //print_r($pager_data);
  // Slice array.
  $results = array_slice($result_fields_merge, $offset, $limit,true);
  //print_r($results);
  $results = theme('islandora_solr_facet_pages_results', array(
    'results' => $results,
    'solr_field' => $solr_set['solr_field'],
    'path' => $path,
    'url_alias' => $url_alias,
  ));

  // Render pager.
  $pager = theme('pager', array(
    'element' => 0,
    'quantity' => 10,
  ));

  if (variable_get('islandora_solr_facet_pages_search_form', FALSE)) {
    $form = drupal_get_form('islandora_solr_facet_pages_search_form', array(
      'path' => $path,
      'prefix' => $prefix,
      'search_term' => $search_term,
      'url_alias' => $url_alias,
    ));
    $search_form = drupal_render($form);
  }
  else {
    $search_form = '';
  }

  return theme('islandora_solr_facet_pages_wrapper', array(
    'search_form' => $search_form,
    'letterer' => $letterer,
    'results' => $results,
    'pager' => $pager,
    'path' => $path,
    'pager_data' => $pager_data,
    'url_alias' => $url_alias,
    'show_a_z' => $show_a_z,
  ));
}

/**
 * Access callback function.
 *
 * @param string $path
 *   Machine readable name passed in the url to decide what solr field to facet
 *   on.
 *
 * @return bool
 *   A boolean based on user access and valid path.
 */
function islandora_solr_facet_pages_access_callback($path = NULL) {
  // Get available fields from variable.
  $fields = variable_get('islandora_solr_facet_pages_fields_data', array());

  // Callback validation.
  foreach ($fields as $key => $value) {
    // Check for allowed paths.
    if ($path == $value['path'] && user_access(ISLANDORA_VIEW_OBJECTS)) {
      
      return TRUE;
    }
  }
  
  return FALSE;
}


/**
 * Callback function to populate the facet page block with links.
 *
 * @return string
 *   Returns a rendered bulletted list with links to all configured facet
 *   pages.
 */
function islandora_solr_facet_pages_block_callback() {
  // Get available fields from variable.
  $fields = variable_get('islandora_solr_facet_pages_fields_data', array());

  $items = array();
  foreach ($fields as $key => $value) {

    $items[] = l($value['label'], $value['url_alias'] . '/' . $value['path'], array(
      'attributes' => array(
        'title' => $value['label'],
      ),
    ));
  }

  if (!empty($items)) {
    return theme('item_list', array(
      'items' => $items,
      'type' => 'ul',
      'attributes' => array(
        'class' => 'islandora-solr-facet-pages-list',
      ),
    ));
  }
  else {
    return FALSE;
  }
}

/**
 * Defines a facet search form for search facets.
 *
 * @param array $form
 *   The Drupal form.
 * @param array $form_state
 *   The Drupal form state.
 * @param array $vars
 *   Current facet variables to use in the search form.
 *
 * @return array
 *   The Drupal form definition.
 */
function islandora_solr_facet_pages_search_form(array $form, array &$form_state, array $vars = array()) {
  $form = array();
  $form_state['storage'] = array(
    'vars' => $vars,
  );
  $form['search_term'] = array(
    '#type' => 'textfield',
    '#title' => t('Search'),
    '#default_value' => (isset($vars['search_term']) ? $vars['search_term'] : ''),
    '#size' => 60,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
  );
  return $form;
}

/**
 * Submit handler for solr facet page search form.
 *
 * @param array $form
 *   The Drupal form.
 * @param array $form_state
 *   The Drupal form state.
 */
function islandora_solr_facet_pages_search_form_submit(array $form, array &$form_state) {
  drupal_goto("{$form_state['storage']['vars']['url_alias']}/{$form_state['storage']['vars']['path']}/{$form_state['storage']['vars']['prefix']}/{$form_state['values']['search_term']}");
}
